language: objective-c
compiler:
- clang
before_script:
- mkdir build
- cd build
- cmake ..
script:
- make
- make test
notifications:
  slack:
    secure: Jp9E6pwQ9OfHGMV5obiDnbfOSeDgGBBhqYsXfkQ2pAfljhYyFuD9b4TozDNZMMdKzQqqK4w6jmwiLyfdek0iACYmmUfzc3rFBWEEG61q2SkzZEcDtUKhm/Q+/4v0wz3ce0xMVrwDY2HmZUh+YuMY8bTkWgQyed/0Tge2EpdxXfWyH/Ulj8T6oQbgB05z2oo+fQjwEiYm5WC1aIhg/xtt0tzpssIFVdIXJfz7GRsMG8OsxT189kqJRwjiUjKc2D1AqsVshqk+0Bez1PaNasKBTujzPDgywLFMgG3ZU7LCwbh9ZHM/crl2eEc4umfOH2o+XGDqw6Od86PrdbSIsmGm1b1I2fZ4KN08Z+k9hM2P2xPsMVYoy+LT+JO4AGT4PC4Cq4n4ocMlPqfMapBZlesH3AbLAy4P0Jjry0EM5t/xoGfN2MZZxXMOQBoH93APe81PdpmiFb7y2JHhqw5zkS6tvzCUOkewT0W4oFvDNk5GDVJxh9RBGRHNB+O8VdrAPAiDhR6XjXaHL+fNgR+OOGGGmpqI8Yy/nbzUdJ5YgKnW4yyOvexLRRK3RiRLvqiRZ6+uow8Yxm+118AOzKNuP5WhVv5cDdRbt0EHXFBR0M5krfzhi1d0Hg4+eonkUy2s3d1zrF7i3YBgGn4Ai1jjLsjbt6bVKoNP5N2GhWDg1w4+pdY=
